// Apache-2.0 (public verifier repo)
//! H5 — bundle-parsing hardening. Replays the committed fuzz corpus
//! (tests/golden/fuzz/, generated by `scripts/gen_fuzz_corpus.py --seed 7
//! --n 30`): every case must be rejected — at the parse boundary or as
//! `verify_bundle == false` — and NOTHING may panic. The Python suite
//! (tests/test_bundle_hardening.py) asserts the same 30 files, which pins
//! the two implementations to identical rejections.

use serde_json::{json, Value};
use std::fs;
use std::path::PathBuf;

fn repo(path: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .join(path)
}

fn load_bundle(name: &str) -> Value {
    serde_json::from_str(&fs::read_to_string(repo("tests/golden/bundles").join(name)).unwrap())
        .unwrap()
}

fn nested(levels: usize) -> Value {
    // direct construction: json!([v]) would re-serialize v on every wrap
    // (recursive to_value), which is itself a stack bomb at depth
    let mut v = Value::String("deep".into());
    for _ in 0..levels {
        v = Value::Array(vec![v]);
    }
    v
}

#[test]
fn fuzz_corpus_rejected_without_panic() {
    let dir = repo("tests/golden/fuzz");
    let mut names: Vec<String> = fs::read_dir(&dir)
        .unwrap()
        .filter_map(|e| e.ok())
        .map(|e| e.file_name().to_string_lossy().into_owned())
        .filter(|n| n.ends_with(".json"))
        .collect();
    names.sort();
    assert_eq!(names.len(), 30, "committed fuzz corpus must hold 30 cases");
    for name in names {
        let raw = fs::read(dir.join(&name)).unwrap();
        match serde_json::from_slice::<Value>(&raw) {
            // parseable hostile JSON: must be NOT VERIFIED — and not panic
            Ok(v) => assert!(!swarrm_verify::verify_bundle(&v), "{name} must NOT verify"),
            // unparseable: rejected at the parse boundary, same outcome as Python
            Err(_) => {}
        }
    }
}

#[test]
fn over_cap_synthetics_rejected_at_the_boundary() {
    // caps IDENTICAL to verify/verifier.py: proof 64, sigs 8, depth 64
    let base = load_bundle("valid_e1.json");
    assert!(swarrm_verify::verify_bundle(&base), "valid_e1 must verify");

    let mut proof = base.clone();
    proof["entries"][0]["inclusion_proof"] = json!(vec!["00"; 65]);
    assert!(!swarrm_verify::verify_bundle(&proof), "proof len 65 over cap");

    let mut sigs = base.clone();
    let sig = sigs["entries"][0]["envelope"]["signatures"][0].clone();
    sigs["entries"][0]["envelope"]["signatures"] = Value::Array(vec![sig; 9]);
    assert!(!swarrm_verify::verify_bundle(&sigs), "8+1 signatures over cap");

    let mut deep = base.clone();
    deep["__depth65__"] = nested(64); // bundle object + 64 = depth 65, one over
    assert!(!swarrm_verify::verify_bundle(&deep), "depth 65 over cap");

    let mut at_cap = base;
    at_cap["__depth64__"] = nested(63); // exactly at the cap — legit unaffected
    assert!(swarrm_verify::verify_bundle(&at_cap), "depth 64 must still verify");
}

#[test]
fn deep_nesting_cannot_overflow_the_stack() {
    // 100k levels — far past any stack. serde_json refuses >128 on parse, so
    // build the Value programmatically the way an embedding host could; the
    // depth guard must bail (at depth 65) long before recursing that far.
    let mut bundle = load_bundle("valid_e1.json");
    bundle["__bomb__"] = nested(100_000);
    assert!(!swarrm_verify::verify_bundle(&bundle));
    // serde_json's own Drop recurses per level and would overflow the 2 MiB
    // test-thread stack — that hazard is the caller's, not the verifier's;
    // leak the bomb so the test measures only verify_bundle.
    std::mem::forget(bundle);
}
