// Apache-2.0 (public verifier repo)
//! H5 — bundle-parsing hardening. Replays the committed fuzz corpus
//! (tests/golden/fuzz/, generated by `scripts/gen_fuzz_corpus.py --seed 7
//! --n 30`): every case must be rejected — at the parse boundary or as
//! `verify_bundle == false` — and NOTHING may panic. The Python suite
//! (tests/test_bundle_hardening.py) asserts the same 30 files, which pins
//! the two implementations to identical rejections.

use serde_json::{json, Value};
use std::fs;
use std::path::PathBuf;

fn repo(path: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).parent().unwrap().join(path)
}

fn load_bundle(name: &str) -> Value {
    serde_json::from_str(&fs::read_to_string(repo("tests/golden/bundles").join(name)).unwrap()).unwrap()
}

fn nested(levels: usize) -> Value {
    // direct construction: json!([v]) would re-serialize v on every wrap
    // (recursive to_value), which is itself a stack bomb at depth
    let mut v = Value::String("deep".into());
    for _ in 0..levels {
        v = Value::Array(vec![v]);
    }
    v
}

#[test]
fn fuzz_corpus_rejected_without_panic() {
    let dir = repo("tests/golden/fuzz");
    let mut names: Vec<String> = fs::read_dir(&dir).unwrap().filter_map(|e| e.ok()).map(|e| e.file_name().to_string_lossy().into_owned()).filter(|n| n.ends_with(".json")).collect();
    names.sort();
    assert_eq!(names.len(), 30, "committed fuzz corpus must hold 30 cases");
    for name in names {
        let raw = fs::read(dir.join(&name)).unwrap();
        // parseable hostile JSON: must be NOT VERIFIED — and not panic.
        // Unparseable input is rejected at the parse boundary, the same
        // outcome as Python, so that arm has nothing left to assert.
        if let Ok(v) = serde_json::from_slice::<Value>(&raw) {
            assert!(!swarrm_verify::verify_bundle(&v), "{name} must NOT verify");
        }
    }
}

#[test]
fn over_cap_synthetics_rejected_at_the_boundary() {
    // caps IDENTICAL to verify/verifier.py: proof 64, sigs 9, depth 64
    let base = load_bundle("valid_e1.json");
    assert!(swarrm_verify::verify_bundle(&base), "valid_e1 must verify");

    let mut proof = base.clone();
    proof["entries"][0]["inclusion_proof"] = json!(vec!["00"; 65]);
    assert!(!swarrm_verify::verify_bundle(&proof), "proof len 65 over cap");

    let mut sigs = base.clone();
    let sig = sigs["entries"][0]["envelope"]["signatures"][0].clone();
    sigs["entries"][0]["envelope"]["signatures"] = Value::Array(vec![sig; 10]);
    assert!(!swarrm_verify::verify_bundle(&sigs), "9+1 signatures over cap");

    let mut deep = base.clone();
    deep["__depth65__"] = nested(64); // bundle object + 64 = depth 65, one over
    assert!(!swarrm_verify::verify_bundle(&deep), "depth 65 over cap");

    let mut at_cap = base;
    at_cap["__depth64__"] = nested(63); // exactly at the cap — legit unaffected
    assert!(swarrm_verify::verify_bundle(&at_cap), "depth 64 must still verify");
}

#[test]
fn front_truncated_or_relabeled_history_is_rejected() {
    let base = load_bundle("b21_authority_valid.json");
    assert!(swarrm_verify::verify_bundle(&base), "control bundle must verify");

    let mut truncated = base.clone();
    let tail = truncated["checkpoint_chain"].as_array().unwrap()[1..].to_vec();
    assert_ne!(tail[0]["checkpoint"]["body"]["prev_hash"], Value::String(String::new()));
    truncated["checkpoint_chain"] = Value::Array(tail);
    assert!(!swarrm_verify::verify_bundle(&truncated), "a signed suffix is not a complete history");

    let mut relabeled = base;
    relabeled["origin"] = Value::String("evd://tenant/t_attacker".into());
    assert!(!swarrm_verify::verify_bundle(&relabeled), "outer origin must bind to signed checkpoints");
}

#[test]
fn deep_nesting_cannot_overflow_the_stack() {
    // 100k levels — far past any stack. serde_json refuses >128 on parse, so
    // build the Value programmatically the way an embedding host could; the
    // depth guard must bail (at depth 65) long before recursing that far.
    let mut bundle = load_bundle("valid_e1.json");
    bundle["__bomb__"] = nested(100_000);
    assert!(!swarrm_verify::verify_bundle(&bundle));
    // serde_json's own Drop recurses per level and would overflow the 2 MiB
    // test-thread stack — that hazard is the caller's, not the verifier's;
    // leak the bomb so the test measures only verify_bundle.
    std::mem::forget(bundle);
}

/// Two engines, one input, one answer.
///
/// Nine inputs got two different verdicts. `verify_bundle` in Python set
/// `anchors_present = bool(raw)`, so a carried but FALSY `anchor_records`
/// (`false`, `0`, `""`, `{}`) meant "no anchors" and skipped validation: Python
/// VERIFIED, this engine NOT VERIFIED. `null` diverged the other way — Python's
/// `.get()` semantics read it as absent, this engine as a malformed member.
///
/// The differential gate covers `derive_vector` vectors, not `verify_bundle`
/// verdicts, so none of it was caught. The Python half of this test is
/// tests/test_engine_parity.py; if you change either engine, change both.
#[test]
fn carried_record_members_agree_with_the_python_engine() {
    let base = load_bundle("valid_e1.json");
    assert!(swarrm_verify::verify_bundle(&base));

    for field in ["anchor_records", "tst_records"] {
        for junk in [json!(false), json!(0), json!(""), json!({}), json!("not-a-list")] {
            let mut b = base.clone();
            b[field] = junk.clone();
            assert!(!swarrm_verify::verify_bundle(&b), "{field} = {junk} is a carried member that is not a list");
        }
        for absent in [json!(null), json!([])] {
            let mut b = base.clone();
            b[field] = absent.clone();
            assert!(swarrm_verify::verify_bundle(&b), "{field} = {absent} means no records — absence never gates");
        }
    }
}

#[test]
fn unverified_timestamp_token_cannot_supply_temporal_authority() {
    let mut bundle = load_bundle("valid_e1.json");
    bundle["tst_records"] = json!([{
        "checkpoint_body_hash": "faa0c83321debd2c295ea2c7e298a2a769fca5dd1c10ba38bba2be457a80d0ac",
        "token_der_b64": "AA==",
        "tsa_url": "https://attacker.invalid/tst",
        "gen_time": "2030-01-01T00:00:00Z",
        "cert_chain_pem": "not a certificate chain",
        "qualified": false
    }]);
    assert!(!swarrm_verify::verify_bundle(&bundle), "a structurally bound but cryptographically invalid TST is not independent time");
}

/// A newline spliced into a DSSE payload changes the bytes, so it must change
/// the answer. Python's `standard_b64decode` discarded it and verified anyway,
/// which also made "flip one byte and the bundle fails" false for that byte.
#[test]
fn noncanonical_base64_in_signed_fields_is_rejected() {
    let base = load_bundle("valid_e1.json");
    for junk in ["\n", " ", "\t", "!", "@"] {
        let mut b = base.clone();
        let p = b["entries"][0]["envelope"]["payload"].as_str().unwrap().to_string();
        b["entries"][0]["envelope"]["payload"] = Value::String(format!("{}{}{}", &p[..8], junk, &p[8..]));
        assert!(!swarrm_verify::verify_bundle(&b), "noncanonical base64 in a DSSE payload");
    }

    let mut checkpoint = base;
    let sig = checkpoint["target_checkpoint"]["sig"].as_str().unwrap().to_string();
    checkpoint["target_checkpoint"]["sig"] = Value::String(format!("!{sig}"));
    assert!(!swarrm_verify::verify_bundle(&checkpoint), "a noncanonical checkpoint signature must not be decoded permissively");
}
